"""add_gyms_table

Revision ID: 3a1b3e4c25be
Revises: efa950c96ae6
Create Date: 2026-07-10 20:11:28.041760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1b3e4c25be'
down_revision: Union[str, Sequence[str], None] = 'efa950c96ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('dias_gracia_default', sa.Integer(), nullable=False),
    sa.Column('moneda_base', sa.String(length=10), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.Column('estado_suscripcion', sa.String(length=20), nullable=False),
    sa.Column('estado_logico', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_gyms_id'), 'gyms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gyms_id'), table_name='gyms')
    op.drop_table('gyms')
    # ### end Alembic commands ###
