"""initial_models

Revision ID: 942c0e770a15
Revises: 
Create Date: 2026-07-08 22:40:22.555026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942c0e770a15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado_logico', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_miembros_cedula_activa', 'miembros', ['cedula'], unique=False, postgresql_where=sa.text('estado_logico = true'))
    op.create_index(op.f('ix_miembros_cedula'), 'miembros', ['cedula'], unique=True)
    op.create_index(op.f('ix_miembros_id'), 'miembros', ['id'], unique=False)
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('precio_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_logico', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_id'), 'planes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado_logico', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asistencias_fecha_entrada', 'asistencias', ['fecha_entrada'], unique=False)
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_table('membresias_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estatus_pago', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_membresias_vencimiento_status', 'membresias_miembros', ['fecha_vencimiento', 'estatus_pago'], unique=False)
    op.create_index(op.f('ix_membresias_miembros_id'), 'membresias_miembros', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membresia_miembro_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('tasa_cambio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('monto_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membresia_miembro_id'], ['membresias_miembros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_membresias_miembros_id'), table_name='membresias_miembros')
    op.drop_index('idx_membresias_vencimiento_status', table_name='membresias_miembros')
    op.drop_table('membresias_miembros')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_index('idx_asistencias_fecha_entrada', table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_planes_id'), table_name='planes')
    op.drop_table('planes')
    op.drop_index(op.f('ix_miembros_id'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_cedula'), table_name='miembros')
    op.drop_index('idx_miembros_cedula_activa', table_name='miembros', postgresql_where=sa.text('estado_logico = true'))
    op.drop_table('miembros')
    # ### end Alembic commands ###
